# ============================================================================
# API GATEWAY - Production Profile
# ============================================================================
# Production settings: optimized, secure

# Resilience4j - Production optimized
resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
    instances:
      userServiceCB:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      userServiceCB:
        baseConfig: default

# CORS - Production origins only
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Correlation-ID
              - X-Trace-ID
            allowCredentials: true
            maxAge: 3600

# Actuator - Minimal exposure
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

# Logging - WARN level
logging:
  level:
    root: WARN
    com.sudagoarth: INFO
    org.springframework.cloud.gateway: WARN

