# ============================================================================
# API GATEWAY - Staging Profile (Pre-Production)
# ============================================================================
# Production-like settings for staging

# Resilience4j - Production-like
resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
    instances:
      userServiceCB:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      userServiceCB:
        baseConfig: default

# CORS - Staging origins only
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Correlation-ID
              - X-Trace-ID
            allowCredentials: true
            maxAge: 3600

# Actuator - Limited exposure
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

# Logging - Info level
logging:
  level:
    root: INFO
    com.sudagoarth: INFO

