# ============================================================================
# USER SERVICE - Local Profile (Development)
# ============================================================================
# Developer-friendly: H2 in-memory, debug logging, relaxed security

spring:
  # H2 In-Memory Database
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
  
  # JPA - Relaxed for local development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Flyway - Disabled (using H2 auto-update)
  flyway:
    enabled: false

# Actuator - All endpoints for debugging
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging - Debug level
logging:
  level:
    root: INFO
    com.sudagoarth: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

